name: ci

on: [ push ]

jobs:


  UnitTest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]

    steps:

      - uses: actions/checkout@v4

      - name: Install docker
        if: contains(matrix.os, 'macos')
        run: |
          brew install docker
          docker run --help

      - name: Start ejabberd in a new container
        run: docker run --name ejabberd -d -p 5222:5222 ghcr.io/processone/ejabberd

      - name: Stop the running container
        run: docker stop ejabberd
