name: ci

on: [ push ]

env:
  JAVA_VERSION: 21

jobs:



  Lint:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest ]
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew ciLint --stacktrace



  UnitTest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]

    steps:

      - uses: actions/checkout@v4

      - name: Install docker
        if: contains(matrix.os, 'macos')
        run: |
          brew install docker
          docker run --help

      - name: Start ejabberd in a new container
        run: docker run --name ejabberd -d -p 5222:5222 ghcr.io/processone/ejabberd

      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew ciUnitTest --stacktrace

      - name: Stop the running container
        run: docker stop ejabberd
