name: ci

on: [ push ]

env:
  JAVA_VERSION: 21

jobs:



  Lint:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest ]
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew ciLint --stacktrace

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v2



  UnitTest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        server: [ Ejabberd, Tigase ]
        os: [ ubuntu-latest ]
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Install docker
        if: contains(matrix.os, 'macos')
        run: |
          brew install docker
          docker run --help

      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew ci${{ matrix.server }}UnitTest --stacktrace
